deployment_enabled: true

docker_registry: docker.io

app:
  name: controller
  namespace: sagasrv-controller
  container_name: sagaxyz/controller

container_image: "{{ docker_registry }}/{{ app.container_name }}:{{ versions.controller }}"
