Parameters:
  ClusterName:
    Type: String
    Description: The name of the cluster.

Resources:
  KarpenterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: KarpenterInstanceProfile
      Roles:
        - Ref: KarpenterNodeRole

  KarpenterNodeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: "KarpenterNodeRole-${ClusterName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

