---
- hosts: eks_clusters
  gather_facts: false

  tasks:
    - name: Update kube config
      ansible.builtin.shell: "aws eks --region {{ aws_region }} update-kubeconfig --name {{ eks_cluster_name }} --kubeconfig {{ k8s_kubeconfig }} --profile {{ aws_profile }}"

    - name: Update kube config under main config file
      ansible.builtin.shell: "aws eks --region {{ aws_region }} update-kubeconfig --name {{ eks_cluster_name }} --profile {{ aws_profile }} --alias {{ eks_cluster_name }}"
